# VARIABLES
# ---------
title: Roland Warmerdam
titleRss: "Roland Warmerdam's Blog"
copyright: "Copyright © 2013 Roland Warmerdam"
githubUrl: "https://github.com/Rowno/rolandwarmerdam.co.nz"


# JEKYLL
# ------
pygments: true
permalink: /:title/
paginate: 5
exclude: ['Makefile', 'README.md', 'psd']
markdown: redcarpet
redcarpet:
    extensions: [
        "fenced_code_blocks",
        "autolink",
        "strikethrough",
        "lax_spacing",
        "space_after_headers",
        "superscript",
        "with_toc_data",
        "hard_wrap"
    ]


# PLUGINS
# -------
lessc: lessc --yui-compress
