# VARIABLES
# ---------
title: "Roland Warmerdam"
titleRss: "Roland Warmerdam's Blog"
copyright: "Copyright © 2011-2013 Roland Warmerdam"
githubRepo: "Rowno/rolandwarmerdam.co.nz"
googleAnalyticsId: "UA-21361814-6"
contentImgDir: "/assets/img/content"


# JEKYLL
# ------
url: "https://rolandwarmerdam.co.nz"
pygments: true
permalink: "/:title/"
paginate: 5
markdown: "redcarpet"
redcarpet:
    extensions: [
        "fenced_code_blocks",
        "autolink",
        "strikethrough",
        "lax_spacing",
        "space_after_headers",
        "superscript",
        "with_toc_data",
        "hard_wrap"
    ]
