title: Roland Warmerdam
rss-title: "Roland Warmerdam's Blog"
author:
    name: Roland Warmerdam
copyright: "Copyright 2012, Roland Warmerdam."

pygments: true
permalink: /:title
paginate: 5
markdown: rdiscount
exclude: ['Makefile', 'README.md']
lessc: lessc --yui-compress
